### ISSUE TITLE
Setup richfaces-plugin fails - ClassNotFoundException

### ISSUE THREAD

**Issue by DarthBonkers** [richfaces/richfaces-forge-plugin#1]
I get the error: **_ERROR**_ [richfaces setup] null. I'm using SeamForge beta1 and Java 1.6.0_23-b05

C:\Users\myuser.forge\plugins\org\richfaces\forge\richfaces-forge-plugin\1.0.0-SNAPSHOT has 3 files:
richfaces-forge-plugin.jar
module.xml
richfaces-forge-plugin.jar.index

Here is the error:

Which version of RichFaces?

  1 - [RichFaces 4.0.0.Final]
  2 - [RichFaces 3.3.3.Final]

 ? Choose an option by typing the number of the selection: 1
Warning:  The encoding 'UTF-8' is not supported by the Java runtime.
Wrote C:\/Users/myuser/workspace/TestRF/src/main/webapp
Wrote C:\/Users/myuser/workspace/TestRF/pom.xml
Wrote C:\/Users/myuser/workspace/TestRF/src/main/webapp/WEB-INF/web.xml
Wrote C:\/Users/myuser/workspace/TestRF/src/main/webapp/404.html
Wrote C:\/Users/myuser/workspace/TestRF/src/main/webapp/500.html
Wrote C:\/Users/myuser/workspace/TestRF/src/main/webapp/index.html
Wrote C:\/Users/myuser/workspace/TestRF/src/main/webapp/forge-logo.png
Wrote C:\/Users/myuser/workspace/TestRF/src/main/webapp/forge-style.css
Wrote C:\/Users/myuser/workspace/TestRF/src/main/webapp/jboss-community.png
Wrote C:\/Users/myuser/workspace/TestRF/src/main/webapp/bkg.gif
Wrote C:\/Users/myuser/workspace/TestRF/src/main/webapp/favicon.ico
**_ERROR**_ [richfaces setup] null
org.jboss.forge.shell.exceptions.CommandExecutionException
        at org.jboss.forge.shell.command.Execution.perform(Execution.java:149)
        at org.jboss.forge.shell.command.fshparser.FSHRuntime.run(FSHRuntime.java:125)
        at org.jboss.forge.shell.command.fshparser.FSHRuntime.run(FSHRuntime.java:63)
        at org.jboss.forge.shell.ShellImpl.execute(ShellImpl.java:698)
        at org.jboss.forge.shell.ShellImpl.doShell(ShellImpl.java:495)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:48)
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:125)
        at org.jboss.forge.shell.ShellImpl$Proxy$_$$_WeldClientProxy.doShell(ShellImpl$Proxy$_$$_WeldClientProxy.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.jboss.weld.util.reflection.SecureReflections$13.work(SecureReflections.java:305)
        at org.jboss.weld.util.reflection.SecureReflectionAccess.run(SecureReflectionAccess.java:54)
        at org.jboss.weld.util.reflection.SecureReflectionAccess.runAsInvocation(SecureReflectionAccess.java:163)
        at org.jboss.weld.util.reflection.SecureReflections.invoke(SecureReflections.java:299)
        at org.jboss.weld.introspector.jlr.WeldMethodImpl.invokeOnInstance(WeldMethodImpl.java:188)
        at org.jboss.weld.introspector.ForwardingWeldMethod.invokeOnInstance(ForwardingWeldMethod.java:59)
        at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:198)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:282)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:265)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:234)
        at org.jboss.weld.manager.BeanManagerImpl.notifyObservers(BeanManagerImpl.java:635)
        at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:622)
        at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:616)
        at org.jboss.forge.shell.Bootstrap$1.run(Bootstrap.java:83)
        at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.jboss.forge.shell.command.Execution.perform(Execution.java:144)
        ... 30 more
Caused by: javax.enterprise.event.ObserverException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

```
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at org.jboss.weld.util.reflection.SecureReflections$16.work(SecureReflections.java:395)
    at org.jboss.weld.util.reflection.SecureReflectionAccess.run(SecureReflectionAccess.java:54)
    at org.jboss.weld.util.reflection.SecureReflectionAccess.runAsInstantiation(SecureReflectionAccess.java:216)
    at org.jboss.weld.util.reflection.SecureReflections.newInstance(SecureReflections.java:390)
    at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
    at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:92)
    at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:214)
    at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:282)
    at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:265)
    at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:234)
    at org.jboss.weld.manager.BeanManagerImpl.notifyObservers(BeanManagerImpl.java:635)
    at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:628)
    at org.jboss.weld.event.EventImpl.fire(EventImpl.java:75)
    at org.richfaces.forge.RichFacesPlugin.setup(RichFacesPlugin.java:58)
    ... 35 more
```

Caused by: java.lang.NoClassDefFoundError: javax/faces/webapp/FacesServlet
        at org.richfaces.forge.RichFacesFacet.isFacesServletDefined(RichFacesFacet.java:148)
        at org.richfaces.forge.RichFacesFacet.installDescriptor(RichFacesFacet.java:93)
        at org.richfaces.forge.RichFacesFacet.install(RichFacesFacet.java:47)
        at org.jboss.forge.project.BaseProject.performInstallation(BaseProject.java:258)
        at org.jboss.forge.project.BaseProject.installFacet(BaseProject.java:172)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:48)
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:125)
        at org.jboss.weld.proxies.Project$-1946286523$Proxy$_$$_WeldClientProxy.installFacet(Project$-1946286523$Proxy$_$$_WeldClientProxy.java)
        at org.jboss.forge.shell.project.FacetInstallationHandler.performInstallation(FacetInstallationHandler.java:121)
        at org.jboss.forge.shell.project.FacetInstallationHandler.install(FacetInstallationHandler.java:97)
        at org.jboss.forge.shell.project.FacetInstallationHandler.installRequest(FacetInstallationHandler.java:75)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.jboss.weld.util.reflection.SecureReflections$13.work(SecureReflections.java:305)
        at org.jboss.weld.util.reflection.SecureReflectionAccess.run(SecureReflectionAccess.java:54)
        at org.jboss.weld.util.reflection.SecureReflectionAccess.runAsInvocation(SecureReflectionAccess.java:163)
        at org.jboss.weld.util.reflection.SecureReflections.invoke(SecureReflections.java:299)
        at org.jboss.weld.introspector.jlr.WeldMethodImpl.invokeOnInstance(WeldMethodImpl.java:188)
        at org.jboss.weld.introspector.ForwardingWeldMethod.invokeOnInstance(ForwardingWeldMethod.java:59)
        at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:198)
        ... 42 more
Caused by: java.lang.ClassNotFoundException: javax.faces.webapp.FacesServlet from [Module "org.richfaces.forge.richfaces-forge-plugin:1.0.0-SNAPSHOT" from local
 module loader @979dce4 (roots: C:\Development\forge-1.0.0-SNAPSHOT\bin..\modules,C:\Users\myuser.forge\plugins)]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:191)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:361)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:333)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:310)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:103)
        ... 68 more

**Comment by gastaldi** [comment]
Please, use the JIRA (http://issues.jboss.org) to file issues on Forge
